import 'package:cloud_firestore/cloud_firestore.dart' as firestore;
import 'enums.dart';

class Staff {
  final String id; // Auto-generated ID
  final String?
  userId; // Link to User model (Firebase Auth UID) - optional for non-system users
  final String employeeId; // Custom employee ID (e.g., EMP001)
  final String fullName;
  final String? photoUrl; // Profile photo URL from Firebase Storage
  final double? photoScale; // Avatar zoom level
  final double? photoOffsetX; // Avatar horizontal offset (-1..1)
  final double? photoOffsetY; // Avatar vertical offset (-1..1)

  // Contact Information
  final String email;
  final String? phoneNumber;
  final String? address;
  final String? emergencyContactName;
  final String? emergencyContactPhone;

  // Personal Information
  final DateTime? dateOfBirth;
  final Gender? gender;
  final String? nationalIdNumber;
  final String? passportNumber;
  final String? country;
  final String? provinceState;

  // Employment Details
  final String department;
  final String position; // Job title
  final UserRole role; // System role (requester, manager, finance, admin)
  final EmploymentType employmentType;
  final EmploymentStatus employmentStatus;
  final DateTime dateOfJoining;
  final DateTime? dateOfLeaving;
  final String? reportingManagerId; // Reference to another Staff ID

  // Financial Information
  final String? bankAccountNumber;
  final String? bankName;
  final String? taxId;
  final double?
  monthlySalary; // Base salary (deprecated - use SalaryBenefits model instead)
  final String?
  currentSalaryBenefitsId; // Reference to current salary benefits record

  // Financial Information
  final double? allowances;
  final double? tithePercentage;
  final double? titheAmount;
  final double? socialSecurityAmount;
  final double? providentFundPercentage;
  final double? providentFundAmount;

  // Authorization & Access
  final double? approvalLimit; // Maximum amount they can approve for vouchers
  final List<String> permissions; // Additional permissions if needed

  // Documents
  final int documentsCount; // Count of uploaded documents (managed separately)

  // Metadata
  final DateTime createdAt;
  final DateTime? updatedAt;
  final String? notes; // Additional notes about the staff member

  Staff({
    required this.id,
    this.userId,
    required this.employeeId,
    required this.fullName,
    this.photoUrl,
    this.photoScale,
    this.photoOffsetX,
    this.photoOffsetY,
    required this.email,
    this.phoneNumber,
    this.address,
    this.emergencyContactName,
    this.emergencyContactPhone,
    this.dateOfBirth,
    this.gender,
    this.nationalIdNumber,
    this.passportNumber,
    this.country,
    this.provinceState,
    required this.department,
    required this.position,
    required this.role,
    required this.employmentType,
    required this.employmentStatus,
    required this.dateOfJoining,
    this.dateOfLeaving,
    this.reportingManagerId,
    this.bankAccountNumber,
    this.bankName,
    this.taxId,
    this.monthlySalary,
    this.currentSalaryBenefitsId,
    this.allowances,
    this.tithePercentage,
    this.titheAmount,
    this.socialSecurityAmount,
    this.providentFundPercentage,
    this.providentFundAmount,
    this.approvalLimit,
    this.permissions = const [],
    this.documentsCount = 0,
    required this.createdAt,
    this.updatedAt,
    this.notes,
  });

  // Factory constructor for creating new staff (ID will be auto-generated by Firestore)
  Staff.create({
    this.userId,
    String? employeeId,
    required this.fullName,
    this.photoUrl,
    this.photoScale,
    this.photoOffsetX,
    this.photoOffsetY,
    required this.email,
    this.phoneNumber,
    this.address,
    this.emergencyContactName,
    this.emergencyContactPhone,
    this.dateOfBirth,
    this.gender,
    this.nationalIdNumber,
    this.passportNumber,
    this.country,
    this.provinceState,
    required this.department,
    required this.position,
    required this.role,
    required this.employmentType,
    required this.employmentStatus,
    required this.dateOfJoining,
    this.dateOfLeaving,
    this.reportingManagerId,
    this.bankAccountNumber,
    this.bankName,
    this.taxId,
    this.monthlySalary,
    this.currentSalaryBenefitsId,
    this.allowances,
    this.tithePercentage,
    this.titheAmount,
    this.socialSecurityAmount,
    this.providentFundPercentage,
    this.providentFundAmount,
    this.approvalLimit,
    this.permissions = const [],
    this.documentsCount = 0,
    DateTime? createdAt,
    this.updatedAt,
    this.notes,
  }) : id = '', // Empty ID to be auto-generated by Firestore
       employeeId =
           employeeId ??
           '', // Empty employee ID to be auto-generated by service
       createdAt = createdAt ?? DateTime.now();

  // Calculate years of service
  int get yearsOfService {
    final endDate = dateOfLeaving ?? DateTime.now();
    return endDate.difference(dateOfJoining).inDays ~/ 365;
  }

  // Check if currently employed
  bool get isActive => employmentStatus == EmploymentStatus.active;

  // Firestore serialization
  Map<String, dynamic> toFirestore() {
    return {
      'userId': userId,
      'employeeId': employeeId,
      'fullName': fullName,
      'photoUrl': photoUrl,
      'photoScale': photoScale,
      'photoOffsetX': photoOffsetX,
      'photoOffsetY': photoOffsetY,
      'email': email,
      'phoneNumber': phoneNumber,
      'address': address,
      'emergencyContactName': emergencyContactName,
      'emergencyContactPhone': emergencyContactPhone,
      'dateOfBirth': dateOfBirth != null
          ? firestore.Timestamp.fromDate(dateOfBirth!)
          : null,
      'gender': gender?.name,
      'nationalIdNumber': nationalIdNumber,
      'passportNumber': passportNumber,
      'country': country,
      'provinceState': provinceState,
      'department': department,
      'position': position,
      'role': role.name,
      'employmentType': employmentType.name,
      'employmentStatus': employmentStatus.name,
      'dateOfJoining': firestore.Timestamp.fromDate(dateOfJoining),
      'dateOfLeaving': dateOfLeaving != null
          ? firestore.Timestamp.fromDate(dateOfLeaving!)
          : null,
      'reportingManagerId': reportingManagerId,
      'bankAccountNumber': bankAccountNumber,
      'bankName': bankName,
      'taxId': taxId,
      'monthlySalary': monthlySalary,
      'currentSalaryBenefitsId': currentSalaryBenefitsId,
      'allowances': allowances,
      'tithePercentage': tithePercentage,
      'titheAmount': titheAmount,
      'socialSecurityAmount': socialSecurityAmount,
      'providentFundPercentage': providentFundPercentage,
      'providentFundAmount': providentFundAmount,
      'approvalLimit': approvalLimit,
      'permissions': permissions,
      'documentsCount': documentsCount,
      'createdAt': firestore.Timestamp.fromDate(createdAt),
      'updatedAt': updatedAt != null
          ? firestore.Timestamp.fromDate(updatedAt!)
          : null,
      'notes': notes,
    };
  }

  factory Staff.fromFirestore(
    firestore.DocumentSnapshot<Map<String, dynamic>> doc,
  ) {
    final data = doc.data();
    if (data == null) {
      throw Exception('Staff document ${doc.id} has no data');
    }

    // Parse dateOfJoining with fallback
    DateTime dateOfJoining;
    if (data['dateOfJoining'] != null && data['dateOfJoining'] is firestore.Timestamp) {
      dateOfJoining = (data['dateOfJoining'] as firestore.Timestamp).toDate();
    } else {
      dateOfJoining = DateTime.now();
    }

    // Parse createdAt with fallback
    DateTime createdAt;
    if (data['createdAt'] != null && data['createdAt'] is firestore.Timestamp) {
      createdAt = (data['createdAt'] as firestore.Timestamp).toDate();
    } else {
      createdAt = DateTime.now();
    }

    return Staff(
      id: doc.id,
      userId: data['userId'] as String?,
      employeeId: data['employeeId'] as String? ?? '',
      fullName: data['fullName'] as String? ?? 'Unknown',
      photoUrl: data['photoUrl'] as String?,
      photoScale: (data['photoScale'] as num?)?.toDouble(),
      photoOffsetX: (data['photoOffsetX'] as num?)?.toDouble(),
      photoOffsetY: (data['photoOffsetY'] as num?)?.toDouble(),
      email: data['email'] as String? ?? '',
      phoneNumber: data['phoneNumber'] as String?,
      address: data['address'] as String?,
      emergencyContactName: data['emergencyContactName'] as String?,
      emergencyContactPhone: data['emergencyContactPhone'] as String?,
      dateOfBirth: data['dateOfBirth'] != null && data['dateOfBirth'] is firestore.Timestamp
          ? (data['dateOfBirth'] as firestore.Timestamp).toDate()
          : null,
      gender: data['gender'] != null
          ? Gender.values.firstWhere((e) => e.name == data['gender'], orElse: () => Gender.other)
          : null,
      nationalIdNumber: (data['nationalIdNumber'] as String?)?.isNotEmpty == true
          ? data['nationalIdNumber'] as String
          : null,
      passportNumber: (data['passportNumber'] as String?)?.isNotEmpty == true
          ? data['passportNumber'] as String
          : null,
      country: (data['country'] as String?)?.isNotEmpty == true
          ? data['country'] as String
          : null,
      provinceState: (data['provinceState'] as String?)?.isNotEmpty == true
          ? data['provinceState'] as String
          : null,
      department: data['department'] as String? ?? 'Unknown',
      position: data['position'] as String? ?? 'Unknown',
      role: UserRole.values.firstWhere(
        (e) => e.name == data['role'],
        orElse: () => UserRole.requester,
      ),
      employmentType: EmploymentType.values.firstWhere(
        (e) => e.name == data['employmentType'],
        orElse: () => EmploymentType.fullTime,
      ),
      employmentStatus: EmploymentStatus.values.firstWhere(
        (e) => e.name == data['employmentStatus'],
        orElse: () => EmploymentStatus.active,
      ),
      dateOfJoining: dateOfJoining,
      dateOfLeaving: data['dateOfLeaving'] != null && data['dateOfLeaving'] is firestore.Timestamp
          ? (data['dateOfLeaving'] as firestore.Timestamp).toDate()
          : null,
      reportingManagerId: data['reportingManagerId'] as String?,
      bankAccountNumber: data['bankAccountNumber'] as String?,
      bankName: data['bankName'] as String?,
      taxId: data['taxId'] as String?,
      monthlySalary: data['monthlySalary']?.toDouble(),
      currentSalaryBenefitsId: data['currentSalaryBenefitsId'] as String?,
      allowances: data['allowances']?.toDouble(),
      tithePercentage: data['tithePercentage']?.toDouble(),
      titheAmount: data['titheAmount']?.toDouble(),
      socialSecurityAmount: data['socialSecurityAmount']?.toDouble(),
      providentFundPercentage: data['providentFundPercentage']?.toDouble(),
      providentFundAmount: data['providentFundAmount']?.toDouble(),
      approvalLimit: data['approvalLimit']?.toDouble(),
      permissions: data['permissions'] != null
          ? List<String>.from(data['permissions'] as List)
          : [],
      documentsCount: data['documentsCount'] as int? ?? 0,
      createdAt: createdAt,
      updatedAt: data['updatedAt'] != null && data['updatedAt'] is firestore.Timestamp
          ? (data['updatedAt'] as firestore.Timestamp).toDate()
          : null,
      notes: data['notes'] as String?,
    );
  }

  // copyWith method for easy updates
  Staff copyWith({
    String? userId,
    String? employeeId,
    String? fullName,
    String? photoUrl,
    double? photoScale,
    double? photoOffsetX,
    double? photoOffsetY,
    String? email,
    String? phoneNumber,
    String? address,
    String? emergencyContactName,
    String? emergencyContactPhone,
    DateTime? dateOfBirth,
    Gender? gender,
    String? nationalIdNumber,
    String? passportNumber,
    String? country,
    String? provinceState,
    String? department,
    String? position,
    UserRole? role,
    EmploymentType? employmentType,
    EmploymentStatus? employmentStatus,
    DateTime? dateOfJoining,
    DateTime? dateOfLeaving,
    String? reportingManagerId,
    String? bankAccountNumber,
    String? bankName,
    String? taxId,
    double? monthlySalary,
    String? currentSalaryBenefitsId,
    double? allowances,
    double? tithePercentage,
    double? titheAmount,
    double? socialSecurityAmount,
    double? providentFundPercentage,
    double? providentFundAmount,
    double? approvalLimit,
    int? documentsCount,
    DateTime? updatedAt,
    String? notes,
  }) {
    return Staff(
      id: id,
      userId: userId ?? this.userId,
      employeeId: employeeId ?? this.employeeId,
      fullName: fullName ?? this.fullName,
      photoUrl: photoUrl ?? this.photoUrl,
      photoScale: photoScale ?? this.photoScale,
      photoOffsetX: photoOffsetX ?? this.photoOffsetX,
      photoOffsetY: photoOffsetY ?? this.photoOffsetY,
      email: email ?? this.email,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      address: address ?? this.address,
      emergencyContactName: emergencyContactName ?? this.emergencyContactName,
      emergencyContactPhone:
          emergencyContactPhone ?? this.emergencyContactPhone,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      gender: gender ?? this.gender,
      nationalIdNumber: nationalIdNumber ?? this.nationalIdNumber,
      passportNumber: passportNumber ?? this.passportNumber,
      country: country ?? this.country,
      provinceState: provinceState ?? this.provinceState,
      department: department ?? this.department,
      position: position ?? this.position,
      role: role ?? this.role,
      employmentType: employmentType ?? this.employmentType,
      employmentStatus: employmentStatus ?? this.employmentStatus,
      dateOfJoining: dateOfJoining ?? this.dateOfJoining,
      dateOfLeaving: dateOfLeaving ?? this.dateOfLeaving,
      reportingManagerId: reportingManagerId ?? this.reportingManagerId,
      bankAccountNumber: bankAccountNumber ?? this.bankAccountNumber,
      bankName: bankName ?? this.bankName,
      taxId: taxId ?? this.taxId,
      monthlySalary: monthlySalary ?? this.monthlySalary,
      currentSalaryBenefitsId:
          currentSalaryBenefitsId ?? this.currentSalaryBenefitsId,
      allowances: allowances ?? this.allowances,
      tithePercentage: tithePercentage ?? this.tithePercentage,
      titheAmount: titheAmount ?? this.titheAmount,
      socialSecurityAmount: socialSecurityAmount ?? this.socialSecurityAmount,
      providentFundPercentage:
          providentFundPercentage ?? this.providentFundPercentage,
      providentFundAmount: providentFundAmount ?? this.providentFundAmount,
      approvalLimit: approvalLimit ?? this.approvalLimit,
      permissions: permissions,
      documentsCount: documentsCount ?? this.documentsCount,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      notes: notes ?? this.notes,
    );
  }
}
