// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCMz7x47_ezSp33b7BTeeST-N5b2DKpYk',
    appId: '1:380309314630:web:0000000000000000000000',
    messagingSenderId: '380309314630',
    projectId: 'hc-petty-cash-report',
    authDomain: 'hc-petty-cash-report.firebaseapp.com',
    storageBucket: 'hc-petty-cash-report.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMz7x47_ezSp33b7BTeeST-N5b2DKpYk',
    appId: '1:380309314630:android:67f93959a81a48a92e7e47',
    messagingSenderId: '380309314630',
    projectId: 'hc-petty-cash-report',
    storageBucket: 'hc-petty-cash-report.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDoe3mEP5xXgDwmf7vMTDdcvfrJqDetBw',
    appId: '1:380309314630:ios:8cd71442961bf1612e7e47',
    messagingSenderId: '380309314630',
    projectId: 'hc-petty-cash-report',
    storageBucket: 'hc-petty-cash-report.firebasestorage.app',
    iosBundleId: 'com.example.hcFinannceReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDoe3mEP5xXgDwmf7vMTDdcvfrJqDetBw',
    appId: '1:380309314630:ios:8cd71442961bf1612e7e47',
    messagingSenderId: '380309314630',
    projectId: 'hc-petty-cash-report',
    storageBucket: 'hc-petty-cash-report.firebasestorage.app',
    iosBundleId: 'com.example.hcFinannceReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCMz7x47_ezSp33b7BTeeST-N5b2DKpYk',
    appId: '1:380309314630:web:0000000000000000000000',
    messagingSenderId: '380309314630',
    projectId: 'hc-petty-cash-report',
    authDomain: 'hc-petty-cash-report.firebaseapp.com',
    storageBucket: 'hc-petty-cash-report.firebasestorage.app',
  );
}
